# Site settings
title: Cheyenne Goh
description: UCalgary Software Engineering Student
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Cheyenne Goh
user_description: I am a third-year student pursuing a BSc in Software Engineering with a minor in Mechatronics from the Schulich School of Engineering at the University of Calgary.
user_title: UCalgary Software Engineering Student
email: cheyennegoh@shaw.ca
github_username: cheyennegoh

exclude: ['package.json', 'src' , 'node_modules']
