# Site settings
title: Cheyenne Goh
description: UCalgary Software Engineering Graduate
# baseurl: "" # the subpath of your site, e.g. /blog
url: http://cheyennegoh.com

# User settings
username: Cheyenne Goh
user_description: I recently graduated from the University of Calgary's Schulich School of Engineering with a Bachelor of Science in Software Engineering and a minor in Mechatronics.
user_title: UCalgary Software Engineering Graduate
email: cheyennegoh@cheyennegoh.com
github_username: cheyennegoh

exclude: ['package.json', 'src' , 'node_modules']
